# PostgreSQL
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/petner}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:petner}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:petner123}
spring.datasource.driver-class-name=${SPRING_DATASOURCE_DRIVER_CLASS_NAME:org.postgresql.Driver}

# Redis - Cache
spring.cache.type=${SPRING_CACHE_TYPE:redis}
spring.data.redis.host=${SPRING_REDIS_CACHE_HOST:localhost}
spring.data.redis.port=${SPRING_REDIS_CACHE_PORT:6379}

# Redis - Session
spring.session.store-type=${SPRING_SESSION_STORE_TYPE:redis}
spring.session.redis.namespace=${SPRING_SESSION_REDIS_NAMESPACE:petner:session}

# JPA
spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
spring.jpa.show-sql=${SPRING_JPA_SHOW_SQL:true}
spring.jpa.properties.hibernate.format_sql=${SPRING_JPA_HIBERNATE_FORMAT_SQL:true}
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Security Configuration
spring.security.user.name=${SPRING_SECURITY_USER_NAME:admin}
spring.security.user.password=${SPRING_SECURITY_USER_PASSWORD:admin123}

# DevTools
spring.devtools.restart.enabled=${SPRING_DEVTOOLS_RESTART_ENABLED:true}
spring.devtools.livereload.enabled=${SPRING_DEVTOOLS_LIVERELOAD_ENABLED:true}

# logging
logging.level.root=${LOGGING_LEVEL_ROOT:INFO}
logging.level.com.example.petner=${LOGGING_LEVEL_PETNER:DEBUG}
logging.level.org.springframework.security=${LOGGING_LEVEL_SECURITY:DEBUG}

# Cookie settings for development (HTTP)
cookie.secure=${COOKIE_SECURE:false}